name: JASPAR-profile-inference
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython>=1.80
  - blast=2.9.0
  - hmmer=3.2.1
  - logomaker
  - matplotlib
  - numpy
  - pandas
  - requests
  - tqdm
  - pip:
    - pyjaspar
